FROM alpine:3.7

ENV PRODUCT iridium

WORKDIR ${PRODUCT}

COPY ./requirements.txt .

RUN apk -U upgrade && \
    apk add \
    git \
    wget \
    python2 \
    py-pip \
    py-idna \
    py-openssl \
    py-cryptography \
    libffi-dev \
    openssl-dev \
    py-virtualenv \
    gcc && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del \
    wget \
    git \
    libffi-dev \
    openssl-dev \
    py-virtualenv \
    py-pip \
    gcc && \
    rm -rvf /var/cache/apk/* && \
    find /usr/ -name *.pyc -exec rm -vf {} \;

COPY ./$PRODUCT.py .

EXPOSE 5000

ENTRYPOINT ["python", "-v", "iridium.py"]

# docker run -e orderTopic=arn:aws:sns:us-east-1:651426287273:ecsworkshop-commit -e monolithUrl=http://foo.example.com -ti client-alpine
